program test
  use test_high_precision_m
  use test_expm_m
  use test_normalization_m
  use test_dual_m
  use test_radau5_m
  use test_newton_m
  use test_matrix_m
  use test_qsort_m
  use test_vector_m
  use test_sqrtm_m
  use test_arnoldi_m
  use test_schur_m
  implicit none

  call test_high_precision
  call test_expm
  call test_normalization
  call test_dual
  call test_radau5
  call test_newton
  call test_matrix
  call test_qsort
  call test_vector
  call test_sqrtm
  call test_arnoldi
  call test_schur
end program
