---
default:
  interruptible: true

workflow:
  auto_cancel:
    on_job_failure: all
    on_new_commit: interruptible
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_TAG

test:
  stage: test
  variables:
    BLAS95ROOT: /usr/share/mkl/blas95
    LAPACK95ROOT: /usr/share/mkl/lapack95
    MKLROOT: /opt/intel/oneapi/mkl/latest
  image: registry.git.rwth-aachen.de/ithe/fargo
  script:
    - |-
      echo '[debug]
      target = "test"
      single = true
      intsize = 32
      idxsize = 32
      libraries = ["ARPACK", "BLAS95", "GMP", "LAPACK95", "MPFR", "MUMPS", "TRIANGLE"]
      templates = [
        { files = [
          "src/test/example.inp",
          "src/test/example_matrix4.dat",
          "src/test/S1.test",
          "src/test/S2.test",
          "src/test/S3.test",
          "src/test/table.csv",
          "src/test/test1.json",
          "src/test/test2.json",
        ] },
      ]
      ' | tee fargo.toml
    - fargo run
