# colors
OFF_COLOR = \e[m
CMD_COLOR = \e[1;37m
INP_COLOR = \e[1;32m
OUT_COLOR = \e[1;36m

RM_P     := $(CMD_COLOR)rm$(OFF_COLOR)
AR_P     := $(CMD_COLOR)ar$(OFF_COLOR)
PYTHON_P := $(CMD_COLOR)$(PYTHON)$(OFF_COLOR)
M4_P     := $(CMD_COLOR)$(M4)$(OFF_COLOR)
FC_P     := $(CMD_COLOR)$(FC)$(OFF_COLOR)
CC_P     := $(CMD_COLOR)$(CC)$(OFF_COLOR)
FIND_P   := $(CMD_COLOR)find$(OFF_COLOR)
FORD_P   := $(CMD_COLOR)ford$(OFF_COLOR)
CHMOD_P  := $(CMD_COLOR)chmod$(OFF_COLOR)
