[project]
  # Not important, will be used to name graph file
  name = "fortran-basic"

  # Optionally provide the source directory, defaults to "$PWD/src"
  # sources = "src"

[compilation]
  # Absolute or relative path to build directory
  # Since the actual compilation takes place in another subdirectory
  # named after the used compiler and mode, the build directory of the
  # "old" Makefile can also be used here.
  build = "build"

  # Either intel or gnu compiler
  compiler = "gnu"

  # Choose between debug, profile and release
  mode = "debug"

[libraries]
  # Set library flags to true to include them when linking the program
  # ILUPACK can not be used together with MUMPS, as it already contains
  # an old version of MUMPS (leads to conflict)
  ARPACK   = false
  EXPOKIT  = false
  FEAST    = false
  ILUPACK  = false
  MUMPS    = false
  QUADPACK = false
  MPFR     = false
  TRIANGLE = true
  SPIKE    = false

[options]
  # Default integer size in bits, must be either 32 or 64
  INTSIZE = 32

  # Integer size of sparse matrix row pointers
  # Either 32 or 64 and at least as big as INTSIZE
  # Use 64 if you work with HUGE matrices (> 2 billion non-zero entries)
  IDXSIZE = 32

[M4]
  # The m4 configuration is general and not compiler specific.
  # Automatic variables: m4_debug, m4_gnu, m4_intel, m4_intsize, m4_idxsize, m4_projectdir
  # Additionally each library will be packed as variable, i.e. QUADPACK -> m4_quadpack
  # M4 = "m4"
  # FLAGS = ["-P", "-s"]
  # Defined variables will be appended to the flags
  # VARS = {}
