[defaults]
sources   = ["lib/fortran-basic/src"]
libraries = ["BLAS95", "LAPACK95", "MPFR", "MUMPS", "ZLIB"]


[debug]
target    = "dd"
args      = "--run {files[0]} --temperature 4.0 --device {files[1]}"
runner    = "slurm"
partition = "fast"
templates = [
  { files = [ "run.ini" ] },
  { files = [ "devices/examples/pmosfet2D.ini" ], action="expand" }
]


[release]
target    = "dd"
args      = "--run {files[0]} --temperature 4.0 --device {files[1]}"
mode      = "release"
runner    = "slurm"
partition = "fast"
templates = [
  { files = [ "run.ini" ] },
  { files = [ "devices/examples/pmosfet2D.ini" ], action="expand" }
]

