[defaults]
sources   = ["lib/fortran-basic/src"]
libraries = ["BLAS95", "LAPACK95", "MPFR", "ZLIB"]


[debug]
target    = "dd"
args      = "--run {files[0]} --temperature 4.0 --device {files[1]}"
runner    = "slurm"
partition = "fast"
templates = [
  { files = [ "run.ini" ] },
  { files = [ "devices/examples/pmosfet2D.ini" ], action="expand" }
]


[release]
target    = "dd"
args      = "--run {files[0]} --temperature 4.0 --device {files[1]}"
mode      = "release"
runner    = "slurm"
partition = "fast"
templates = [
  { files = [ "run.ini" ] },
  { files = [ "devices/examples/pmosfet2D.ini" ], action="expand" }
]


[test]
target    = "test"
sources   = ["test"]
templates = [
  { files = [ "test/devices/cap1D.ini" ] },
  { files = [ "test/devices/cap1DpermShift.ini" ] },
  { files = [ "test/devices/1Dtransport.ini" ] },
  { files = [ "test/devices/cap2D.ini" ] },
  { files = [ "test/devices/2Dtransport.ini" ] },
  { files = [ "test/devices/cap3D.ini" ] }
]


[schottky_test]
mode = "debug"
target = "schottky_test"
sources = ["lib/fortran-basic/src", "test"]
runner = "slurm"
partition = "fast"
args = ""
templates = [
  { files = [ "test/devices/schottky1D.ini" ], action = "expand" }
]


[material_test]
mode = "debug"
target = "material_test"
sources = ["lib/fortran-basic/src", "test"]
args = ""
templates = [
  { files = [
      "test/devices/two_material_parse.ini",
      "test/devices/two_material_missing_name.ini",
      "test/devices/two_material_uniformity.ini",
      "test/devices/two_material_unknown.ini"
  ], action = "expand" }
]


[het_test]
mode    = "debug"
target  = "het_test"
sources = ["lib/fortran-basic/src", "test"]
runner  = "slurm"
partition = "fast"
args    = ""
templates = [
  { files = [ "devices/het/si_sige.ini" ], action = "expand" }
]


[het_jacobian_test]
mode    = "debug"
target  = "het_jacobian_test"
sources = ["lib/fortran-basic/src", "test"]
runner  = "slurm"
partition = "fast"
args    = ""
templates = [
  { files = [ "devices/het/si_sige.ini" ], action = "expand" }
]


[jacobian_validation_test]
mode    = "debug"
target  = "jacobian_validation_test"
sources = ["lib/fortran-basic/src", "test"]
args    = ""
